steps:
  - name: 'python:3.12'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install uv
        uv sync
        uv run pytest app/tests/ -v

options:
  logging: 'CLOUD_LOGGING_ONLY'